CC = g++
CFLAGS = -std=c++11 -g -I..

all: test1-1 test1-2 test1-3 test1-4 test1-5 test1-6 test1-7 test1-8

test1-1: test1-1.cpp validate.h ../RBTree.h ../Node.h
	$(CC) $(CFLAGS) -o $@ $<
test1-2: test1-2.cpp validate.h ../RBTree.h ../Node.h
	$(CC) $(CFLAGS) -o $@ $<
test1-3: test1-3.cpp validate.h ../RBTree.h ../Node.h
	$(CC) $(CFLAGS) -o $@ $<
test1-4: test1-4.cpp validate.h ../RBTree.h ../Node.h
	$(CC) $(CFLAGS) -o $@ $<
test1-5: test1-5.cpp validate.h ../RBTree.h ../Node.h
	$(CC) $(CFLAGS) -o $@ $<
test1-6: test1-6.cpp validate.h ../RBTree.h ../Node.h
	$(CC) $(CFLAGS) -o $@ $<
test1-7: test1-7.cpp validate.h ../RBTree.h ../Node.h
	$(CC) $(CFLAGS) -o $@ $<
test1-8: test1-8.cpp validate.h ../RBTree.h ../Node.h
	$(CC) $(CFLAGS) -o $@ $<

clean:
	rm *.out total.txt test1-1 test1-2 test1-3 test1-4 test1-5 test1-6 test1-7 test1-8
